---
title: "table3"
author: "Harrison"
date: "December 12, 2020"
output: pdf_document
---

```{r Setting WD}
library(tidyverse)
library(haven)
library(rdrobust)
library(AER)
library(ivpack)
<<<<<<< HEAD
#setwd("C:/Users/lucas/Documents/CMU/3_Junior Year/Fall/Metrics II 73374/__Final Project/374-Final-Project/Admin Stuff/aer_replication/data/19th")
=======

#setwd("~/Econometrics 2/374-Final-Project/aer_replication/data/19th")

setwd("C:/Users/lucas/Documents/CMU/3_Junior Year/Fall/Metrics II 73374/__Final Project/374-Final-Project/Admin Stuff/aer_replication/data/19th")

>>>>>>> 91dd2e27685289a6519ce675bf6027cd11826992
df64 <- read_dta("Merged_1853_1864_data.dta")
df <- df64
```

```{r Cleaning data}
df$dist_netw <- df$dist_netw/100
#df$dist_netw2 <- (df$dist_netw)^2
#df$dist_netw3 <- (df$dist_netw)^3

df$dist2 <- ifelse(df$broad ==0,-df$dist_netw,df$dist_netw )

m64 = rdbwselect(y = df$log_rentals_1864, x = df$dist2, vce = "nn", cluster = df$block)
```

```{r Column 1}
#covariates
covs2 <- cbind(df$dist_cent, df$dist_urinal,df$old_sewer, df$dist_pump)

#fitting fuzzy LLR
B21 <- rdrobust(df$log_rentals_1864, x = df$dist2,fuzzy = df$death_ind, covs = covs2, vce = "nn", cluster = df$block)
summary(B21)

#Coefficients, Transformed exp(beta)-1, SE
B21$coef[1,1]
B21brack = exp(B21$coef[1,1])-1
B21$se[1,1]

#Number of Obs, Mean outside BSP, BW
B21$N_h
df %>%
  filter(broad == 0 & dist_netw < B21$bws[1]) %>%
  summarise(avg = mean(rentals_64, na.rm = TRUE))
100*B21$bws[1]

```

```{r Column 2}
#covariates
covs2 <- cbind(df$dist_cent, df$dist_urinal,df$old_sewer, df$dist_pump)

#fitting fuzzy LLR
B22 <- rdrobust(df$log_rentals_1864, x = df$dist2,fuzzy = df$death_ind, p =3,  h = 0.33, covs = covs2, vce = "nn", cluster = df$block)
summary(B22)

#Coefficients, Transformed exp(beta)-1, SE
B22$coef[1,1]
B22brack = exp(B22$coef[1,1])-1
B22$se[1,1]

#Number of Obs, Mean outside BSP, BW
B22$N_h
df %>%
  filter(broad == 0 & dist_netw < B22$bws[1]) %>%
  summarise(avg = mean(rentals_64, na.rm = TRUE))
100*B22$bws[1]
```

```{r Column 3}
#covariates
covs2 <- cbind(df$dist_cent, df$dist_urinal,df$old_sewer, df$dist_pump)

#fitting fuzzy LLR
B23 <- rdrobust(df$log_rentals_1864, x = df$dist2,fuzzy = df$death_ind, p =2,  h = 1, covs = covs2, vce = "nn", cluster = df$block)
summary(B23)

#Coefficients, Transformed exp(beta)-1, SE
B23$coef[1,1]
B23brack = exp(B23$coef[1,1])-1
B23$se[1,1]

#Number of Obs, Mean outside BSP, BW
B23$N_h
df %>%
  filter(broad == 0 & dist_netw < B23$bws[1]) %>%
  summarise(avg = mean(rentals_64, na.rm = TRUE))
100*B23$bws[1]
```

```{r Column 4}

#filter df for houses with 29.2 m
temp1 <- df %>% 
  filter(dist_netw < 0.292)

#fitting IV reg

<<<<<<< HEAD
#instruments on right, endogenous on left, exogenous on both
B24 <- ivreg(log_rentals_1864 ~ death_ind  + dist_urinal + old_sewer + dist_pump
             | dist_urinal + old_sewer + dist_pump + broad + dist_broad + broad*dist_broad
             , data = temp1) #need to cluster on block SE
summary(B24)

library(sanwich)
sqrt(diag(vcovCL(B24, cluster = ~ block)))
=======
B24 <- ivreg(log_rentals_1864 ~ death_ind  + dist_urinal + old_sewer + dist_pump| dist_urinal + old_sewer + dist_pump + broad + dist_broad + broad*dist_broad, data = temp1) #need to cluster on block SE
summary(B24)

>>>>>>> 91dd2e27685289a6519ce675bf6027cd11826992

#Coefficients, Transformed exp(beta)-1, SE
B24$coefficients[2]
B24brack = exp(B24$coef[2])-1

#SE
se4 <- sqrt(diag(vcovCL(B24, cluster = ~ block)))
se4[2]


#Number of Obs, Mean outside BSP, BW

B24$n 

df %>% 
  filter(broad == 0 & dist_netw < 0.292) %>% 
  summarize(mean1 = mean(rentals_64, na.rm = TRUE))

29.2

summary(B24, diagnostics =  TRUE)
```

```{r Column 5}
#filter df for houses with 29.2 m
temp1 <- df %>% 
  filter(dist_netw < 0.292)

#fitting IV reg

<<<<<<< HEAD
B25 <- ivreg(log_rentals_1864 ~ deaths  + dist_urinal + old_sewer + dist_pump
             | dist_urinal + old_sewer + dist_pump + broad + dist_broad + broad*dist_broad
             , data = temp1) #need to cluster on block SE #need to cluster on block SE
summary(B25)

sqrt(diag(vcovCL(B25, cluster = ~ block)))
=======
B25 <- ivreg(log_rentals_1864 ~ deaths  + dist_urinal + old_sewer + dist_pump| dist_urinal + old_sewer + dist_pump + broad + dist_broad + broad*dist_broad, data = temp1) #need to cluster on block SE
summary(B25)

>>>>>>> 91dd2e27685289a6519ce675bf6027cd11826992

#Coefficients, Transformed exp(beta)-1, SE
B25$coefficients[2]
B25brack = exp(B25$coef[2])-1

#SE
se5 <- sqrt(diag(vcovCL(B25, cluster = ~ block)))
se5[2]


#Number of Obs, Mean outside BSP, BW

B25$n 

df %>% 
  filter(broad == 0 & dist_netw < 0.292) %>% 
  summarize(mean1 = mean(rentals_64, na.rm = TRUE))

29.2

summary(B25, diagnostics =  TRUE)
```