```{r}
library(haven)
library(tidyverse)
library(sandwich)
library(tidyverse)
library(foreign)
library(readstata13)
library(lmtest)
```

# Causal Graphs 
```{r}
library(dagitty) #Analyzes causal diagrams
library(ggdag) #Allows drawing diagrams for use with dagitty
#Represent all equations in Sewall Wright's diagram
AFG<-dagify(Y~X+C+W,
C ~ X + BSP)

ggdag(AFG)+theme_dag_blank()+labs(title="Causal Graph for AFG")

impliedConditionalIndependencies(AFG)
```




#Table B2: Fuzzy RD

```{r Setting WD}
library(tidyverse)
library(haven)
library(rdrobust)
library(AER)
setwd("C:/Users/lucas/Documents/CMU/3_Junior Year/Fall/Metrics II 73374/__Final Project/374-Final-Project/Admin Stuff/aer_replication/data/19th")
df64 <- read_dta("Merged_1853_1864_data.dta")
df <- df64
```


```{r Cleaning data}
df$dist_netw <- df$dist_netw/100
#df$dist_netw2 <- (df$dist_netw)^2
#df$dist_netw3 <- (df$dist_netw)^3

df$dist2 <- ifelse(df$broad ==0,-df$dist_netw,df$dist_netw )

m64 = rdbwselect(y = df$log_rentals_1864, x = df$dist2, vce = "nn", cluster = df$block)
```

```{r Column 1}
#covariates
covs2 <- cbind(df$dist_cent, df$dist_urinal,df$old_sewer, df$dist_pump)

#fitting fuzzy LLR
B21 <- rdrobust(df$log_rentals_1864, x = df$dist2,fuzzy = df$death_ind, covs = covs2, vce = "nn", cluster = df$block)
summary(B21)

#Coefficients, Transformed exp(beta)-1, SE
B21$coef[1,1]
B21brack = exp(B21$coef[1,1])-1
B21$se[1,1]

#Number of Obs, Mean outside BSP, BW
B21$N_h
df %>%
  filter(broad == 0 & dist_netw < B21$bws[1]) %>%
  summarise(avg = mean(rentals_64, na.rm = TRUE))
100*B21$bws[1]

```

```{r Column 2}
#covariates
covs2 <- cbind(df$dist_cent, df$dist_urinal,df$old_sewer, df$dist_pump)

#fitting fuzzy LLR
B22 <- rdrobust(df$log_rentals_1864, x = df$dist2,fuzzy = df$death_ind, p =3,  h = 0.33, covs = covs2, vce = "nn", cluster = df$block)
summary(B22)

#Coefficients, Transformed exp(beta)-1, SE
B22$coef[1,1]
B22brack = exp(B22$coef[1,1])-1
B22$se[1,1]

#Number of Obs, Mean outside BSP, BW
B22$N_h
df %>%
  filter(broad == 0 & dist_netw < B22$bws[1]) %>%
  summarise(avg = mean(rentals_64, na.rm = TRUE))
100*B22$bws[1]
```
```{r Column 3}
#covariates
covs2 <- cbind(df$dist_cent, df$dist_urinal,df$old_sewer, df$dist_pump)

#fitting fuzzy LLR
B23 <- rdrobust(df$log_rentals_1864, x = df$dist2,fuzzy = df$death_ind, p =2,  h = 1, covs = covs2, vce = "nn", cluster = df$block)
summary(B23)

#Coefficients, Transformed exp(beta)-1, SE
B23$coef[1,1]
B23brack = exp(B23$coef[1,1])-1
B23$se[1,1]

#Number of Obs, Mean outside BSP, BW
B23$N_h
df %>%
  filter(broad == 0 & dist_netw < B23$bws[1]) %>%
  summarise(avg = mean(rentals_64, na.rm = TRUE))
100*B23$bws[1]
```

```{r Column 4}
library(lmtest)
library(sandwich)
#Need to cluster on block

df$

#filter df for houses with 29.2 m
temp1 <- df %>% 
  filter(dist_netw < 0.292)

#fitting IV reg
#instruments on right, endogenous on left, exogenous on both
firstStage = lm(broad~ death_ind + dist_urinal + old_sewer + dist_pump, data = temp1)
summary(firstStage)

B24 <- ivreg(log_rentals_1864 ~ death_ind  + dist_urinal + old_sewer + dist_pump
             | dist_urinal + old_sewer + dist_pump + broad + dist_broad + broad*dist_broad
             , data = temp1) #need to cluster on block SE
summary(B24)

se <- sqrt(diag(vcovCL(B24, cluster = ~ block)))
se
           
#Coefficients, Transformed exp(beta)-1, SE
B24$coefficients[2]
B24brack = exp(B24$coef[2])-1

#B24$se[1,1] Need to extract se from ivreg, can hard code

#Number of Obs, Mean outside BSP, BW

B24$n

df %>% 
  filter(broad == 0 & dist_netw < 0.292) %>% 
  summarize(mean1 = mean(rentals_64, na.rm = TRUE))
29.2
```

```{r Column 5}
#Need to cluster on block

#filter df for houses with 29.2 m
temp1 <- df %>% 
  filter(dist_netw < 0.292)

#fitting IV reg

B25 <- ivreg(log_rentals_1864 ~ deaths  + dist_urinal + old_sewer + dist_pump| dist_urinal + old_sewer + dist_pump + broad + dist_broad + broad*dist_broad, data = temp1) #need to cluster on block SE
summary(B25)

#Coefficients, Transformed exp(beta)-1, SE
B25$coefficients[2]
B25brack = exp(B25$coef[2])-1

se2 <- sqrt(diag(vcovCL(B25, cluster = ~ block)))
se2#Number of Obs, Mean outside BSP, BW

B25$n

df %>% 
  filter(broad == 0 & dist_netw < 0.292) %>% 
  summarize(mean1 = mean(rentals_64, na.rm = TRUE))
29.2
```

# Sargan Hansen Test

```{r}
summary(B24, diagnostics =  TRUE)
summary(B25, diagnostics =  TRUE)
```

```{r}
rdplot(temp1$dist_pump, temp1$dist2)
```


# Additional Specifications


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(tidyverse)
library(rdrobust)
library(rdd)

setwd("C:/Users/lucas/Documents/CMU/3_Junior Year/Fall/Metrics II 73374/__Final Project/374-Final-Project/Admin Stuff/aer_replication/data/19th")
houses = read_dta("Merged_1853_1864_data.dta")

```

```{r}
houses$temp = ifelse(houses$broad == 0, -houses$dist_netw/100, houses$dist_netw/100)
houses$dist_netw = houses$dist_netw/100
houses$dist2 = ifelse(houses$broad == 0, -houses$dist_netw, houses$dist_netw)

m = rdrobust(y = houses$log_rentals_1853, x = houses$dist2, vce = "nn", cluster = houses$block)

m3 = lm.cluster(data = houses[houses$dist_netw < m$bws[1], ], cluster = "block",
                log_rentals_1853 ~ broad + dist_netw + dist_netw2 + dist_cent + dist_square + 
                  dist_fire + dist_thea + dist_police + dist_urinal + dist_pub + dist_church + dist_bank + 
                  no_sewer + old_sewer + dist_vent + dist_pump + dist_pit_fake)

summary(m3)

spec = lm.cluster(data = houses[houses$dist_netw < m$bws[1], ], cluster = "block",
                log_rentals_1853 ~ broad + dist_netw + dist_netw2 + dist_cent + dist_square + 
                  dist_fire + dist_thea + dist_police + dist_urinal + dist_pub + dist_church + dist_bank + 
                  no_sewer + old_sewer + dist_vent + dist_pump + dist_pit_true)
summary(spec)

houses %>%
  filter(broad == 0 )%>%
  summarise(avg = mean(dist_pit_fake, na.rm = TRUE)) 

houses %>%
  filter(broad == 1 )%>%
  summarise(avg = mean(dist_pit_fake, na.rm = TRUE)) 

houses %>%
  filter(broad == 0 )%>%
  summarise(avg = mean(dist_pit_true, na.rm = TRUE)) 

houses %>%
  filter(broad == 1 )%>%
  summarise(avg = mean(dist_pit_true, na.rm = TRUE)) 
```


# Figure B3: False Boundaries


```{r}
setwd("C:/Users/lucas/Documents/CMU/3_Junior Year/Fall/Metrics II 73374/__Final Project/374-Final-Project/Admin Stuff/aer_replication/data/other")

houses <- read_dta("falsification_final.dta")

#houses$dist_fake1 = houses$dist_fake1/100
houses$dist2 <- houses$dist_fake1 
houses$dist2 = ifelse(houses$fake1 == 0, -houses$dist_fake1, houses$dist_fake1)
```

```{r}
#panel A, column 1
#houses$dist_fake1 = houses$dist_fake1/100
houses$dist2 <- houses$dist_fake1 
houses$dist2 = ifelse(houses$fake1 == 0, -houses$dist_fake1, houses$dist_fake1)

controls = cbind(houses$dist_fake1_2)

m = rdrobust(y = houses$log_rentals_1853, x = houses$dist2, covs = NULL, vce = "nn", cluster = houses$block)
summary(m)


m_coef = m$coef[1]

m_se = m$se[1]

m_bw = m$bws[1]

m_obs <- houses[houses$dist_fake1 < m_bw,] %>%
  select(log_rentals_1853, broad, dist_fake1, dist_fake1_2, dist_cent, dist_square,
                  dist_fire, dist_thea, dist_police, dist_urinal, dist_pub, dist_church, dist_bank,
                  no_sewer, old_sewer, dist_vent, dist_pump, dist_pit_fake) %>%
  drop_na() %>%
  nrow()

m_rent_mean <- houses %>%
  filter(broad == 0 & dist_fake1 < m_bw) %>%
  summarise(avg = mean(rentals_53, na.rm = TRUE)) %>%
  as.numeric()

m_bw = m_bw*100
```

```{r Controls and RdRobust}
controls = cbind(houses$dist_cent, houses$dist_square, houses$dist_fire, houses$dist_thea, houses$dist_police,
                 houses$dist_urinal, houses$dist_pub, houses$dist_church, houses$dist_bank,
                 houses$no_sewer, houses$old_sewer, houses$dist_vent, houses$dist_pump, houses$dist_pit_fake)
m2 = rdrobust(y = houses$log_rentals_1853, x = houses$dist2, covs = controls, vce = "nn", cluster = houses$block)
summary(m2)
```

```{r Panel A Col 1}

broad0 <- houses[houses$broad == 0, ]

m = rdrobust(y = broad0$log_rentals_1853, x = broad0$dist2, vce = "nn", cluster = broad0$block)
summary(m)

m3 = lm.cluster(data = houses[houses$dist_fake1 < .26, ], cluster = "block",
                log_rentals_1853 ~ fake1 + dist_fake1 + dist_fake1_2 + dist_cent + dist_square + 
                  dist_fire + dist_thea + dist_police + dist_urinal + dist_pub + dist_church + dist_bank + 
                  no_sewer + old_sewer + dist_vent + dist_pump + dist_pit_fake)
summary(m3)

m3_coef = m3$lm_res$coefficients[2]
m3_se = summary(m3)[2,2]

m3_obs = houses[houses$dist_fake1 <.26,] %>%
  select(log_rentals_1853, fake1,dist_fake1, dist_fake1_2, dist_cent, dist_square, dist_fire, dist_thea, dist_police, dist_urinal, dist_pub, dist_church, dist_bank,no_sewer, old_sewer, dist_vent, dist_pump, dist_pit_fake) %>%
  drop_na() %>%
  nrow()
```

