---
title: "table 1 replication"
author: "Harrison"
date: "December 9, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(tidyverse)
library(sandwich)
library(miceadds)
library(stargazer)
library(rdrobust)
library(rdd)

#Harrison WD
#setwd("~/Econometrics 2/374-Final-Project/aer_replication/data/19th")

#Lucas WD
setwd("C:/Users/lucas/Documents/CMU/3_Junior Year/Fall/Metrics II 73374/__Final Project/374-Final-Project/Admin Stuff/aer_replication/data/19th")

houses = read_dta("houses_1853_final.dta")

```

```{r Cleaning Data}
#full sample
houses$taxexon = ifelse(is.na(houses$tax1), 0, 1)
houses = houses %>%
  select(lnrentals, lntax, taxexon, sewer1, sewer2, sewer4, dist_pump, dist_cent, dist_pit_fake, 
         dist_square, dist_church, dist_police, dist_fire, dist_thea, dist_pub, dist_urinal, dist_vent, 
         dist_school, dist_bank, dist_broad, dist_netw, broad, block)
in_broad_table1 <- houses %>%
  filter(broad == 1)

out_broad_table1 <- houses %>%
  filter(broad == 0)

apply(in_broad_table1, 2, mean, na.rm = T)

```

```{r Split by 100m bandwidth}
#within 100 meters
houses100 = houses %>%
  filter(dist_netw < 1)

houses100_in_broad_table1 <- houses100 %>%
  filter(broad == 1)

houses100_out_broad_table1 <- houses100 %>%
  filter(broad == 0)

summary(houses100_in_broad_table1)
```


```{r Find correct SE function}
#find the right SE function

testlm <- lm.cluster(data = houses, lntax~broad, cluster = "block")
summary(testlm)

```

```{r Columns 1-6}
#in_broad_df (first column)
test = houses %>%
  select(-dist_broad, -dist_netw, -broad, -block)


#get the means
in_all_mean = apply(in_broad_table1, 2, mean, na.rm = T)
out_all_mean = apply(out_broad_table1, 2, mean, na.rm = T)

in_all_mean = in_all_mean[1:19]
out_all_mean = out_all_mean[1:19]

in_100_mean = apply(houses100_in_broad_table1, 2, mean, na.rm = T)[1:19]
out_100_mean = apply(houses100_out_broad_table1, 2, mean, na.rm = T)[1:19]

#get the standard errors

#first we do it on the full sample

se_vec_full = c()
n = length(names(houses))
for (i in 1:n) {
  m = lm.cluster(data = houses, houses[[i]]~broad, cluster = "block")
  se_vec_full = append(se_vec_full, summary(m)[2,2])
}

#now we do it on the within 100 m sample
se_vec_100 = c()
n = length(names(houses100))
for (i in 1:n) {
  m = lm.cluster(data = houses100, houses100[[i]]~broad, cluster = "block")
  se_vec_100 = append(se_vec_100, summary(m)[2,2])
}

#the last 4 se's are for variables that don't need to be included in the table
se_vec_100 = se_vec_100[1:19]
se_vec_full = se_vec_full[1:19]

```

```{r Columns 7-8}

bw_table1 = c()
houses$dist_netw <- ifelse(houses$broad == 0, -houses$dist_netw, houses$dist_netw )

for (i in 1:19) {
  rdbwselectOBJ = rdbwselect(y = houses[[i]], x = houses$dist_netw)
  bw_table1 = append(bw_table1, rdbwselectOBJ$bws[1])
}

table1_bw <- mean(bw_table1)

houses$temp = abs(houses$dist_netw)

m <- rdrobust(y = houses$sewer4, x = houses$dist_netw, h = .297, vce = "hc0", cluster = houses$block)
summary(m)

rd_est_vec = c()
rd_se_vec = c()

for (i in 1:19) {
  m <- rdrobust(y = houses[[i]], x = houses$dist_netw, h = .297, vce = "hc0", cluster = houses$block)
  rd_est_vec = append(rd_est_vec, m$Estimate[1])
  rd_se_vec = append(rd_se_vec, m$se[1])
}
```


```{r Actual Table, results = 'asis'}

names(in_all_mean) <- c("Rental Price (in logs)", "Tax assessed (in logs)", "Tax exonerated (yes = 1)", "Sewer Access: Old/existing",
"Sewer Access: New sewer", "Sewer Access: No access", "Closest pump Dist.(m/100)", "Soho centroid Dist.(m/100)", "Pres. plague pit Dist.(m/100)", "Public square Dist.(m/100)", "Church Dist.(m/100)", "Police station Dist.(m/100)", "Fire station Dist.(m/100)", "Theater Dist.(m/100)", "Pub Dist.(m/100)", "Urinal Dist.(m/100)", "Sewer vent Dist.(m/100)", "Primary school Dist.(m/100)", "Bank Dist.(m/100)")

test = data.frame(
  Full_In = in_all_mean,
  Out = out_all_mean,
  SE = se_vec_full,
  Within_100m_In = in_100_mean,
  Out = out_100_mean,
  SE = se_vec_100,
  RD_Est = rd_est_vec[1:19],
  SE = rd_se_vec[1:19]
)
stargazer(test, summary = FALSE)

```


